# network
bind 0.0.0.0 # menentukan alamat IP yang dizinkan 0.0.0.0 artinya mengizinkan semuanya tetapi karena redisnya berada di container jadi tetap harus melalui container tersebut
port 6379 # menentukan port listen redis (default 6379)

# docker logging
daemonize no # membuat redis berjalan di foreground
logfile "" # menentukan letak log redis dicatat, dikosongkan supaya log redis dapat dibaca menggunakan docker logs
loglevel notice # menentukan tingkat detail log yang di catat 

# RDB
# cara Redis menyimpan data dengan membuat snapshot secara berkala lalu menyimpannya ke dalam file di disk
save 3600 1 # menyimpan snapshot data ke disk jika minimal ada 1 key yang berubah dalam waktu 1 jam
save 300 100 # menyimpan snapshot data ke disk jika minimal ada 100 key yang berubah dalam waktu 5 menit
save 60 10000 # menyimpan snapshot data ke disk jika minimal ada 10000 key yang berubah dalam waktu 1 menit

# AOF
# cara Redis mencatat setiap ada perintah write (perintah yang menambah/mengubah data) yang masuk
appendonly yes # menyimpan data catatan perintah write secara terus-menerus agar data lebih aman
appendfsync everysec # mencatat data ke disk setiap 1 detik sekali

# memory management
maxmemory 100mb # membatasi penggunaan maksimal memori Redis sebesar 100 megabita
maxmemory-policy allkeys-lru # menentukan aturan bahwa jika memori penuh, Redis akan menghapus seluruh yang paling lama tidak digunakan (Least Recently Used)
# volatile dan allkeys: volatile akan menargetkan key yang memiliki masa kadaluwarsa untuk dihapus sedangakan allkeys akan menghapus keseluruhan key
# LRU, LFU, dan LRM: LRU(least recently used) redis akan menghapus key yang paling lama tidak di gunakan, LFU(least frequently used) redis akan menghapus key yang jarang digunakan, dan LRM(least recently modified) redis akan menghapus key yang paling lama tidak di modifikasi.

protected-mode yes # mengamankan akses redis supaya hanya dapat diakses dengan login terlebih dahulu sesuai dengan user yang sudah dibuat

# user management
# auth adalah perintah redis cli untuk client melakukan login
# ACL (acces control sistem) perintah untuk mengelola user di redis
user default off # menonaktifkan user default
user superuser on >super123 ~:* &:* +@all # membuat user bernama superuser dengan password 'super123' yang akan otomatis di hash oleh redis menggunakan >, dan dizinkan mengakses semua key, channel dan perintah yang ada
user eventhub on >event123 resetchannels ~eventhub:* +@string +ping +del # membuat user bernama eventhub dengan password 'event123' yang akan otomatis di hash oleh redis menggunakan >, dan hanya dizinkan mengakses key yang diawali dengan 'eventhub' lalu hanya boleh menjalankan perintah yang berhubungan dengan tipe data string, lalu perintah ping dan del.